<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/0423.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
資料科學的研究流程(循環、非線性):
資料載入。
資料清理。
資料轉換。
資料視覺化。
模型。
溝通。
'''

'\n資料科學的研究流程(循環、非線性):\n資料載入。\n資料清理。\n資料轉換。\n資料視覺化。\n模型。\n溝通。\n'

In [2]:
'''
機器學習的定義:三個要素、一個但書
[要素]
experience E (訓練資料/歷史資料)
tasks T (目的性)
performance measure P (準確度)
[但書]
if its performance at tasks in T, as measured by P,
improves with experience E.
(它在任務T中的表現(由指標P來衡量)，會隨著經驗E的增加而提升。)
'''

'\n機器學習的定義:三個要素、一個但書\n[要素]\nexperience E (訓練資料/歷史資料)\ntasks T (目的性)\nperformance measure P (準確度)\n[但書]\nif its performance at tasks in T, as measured by P,\nimproves with experience E.\n(它在任務T中的表現(由指標P來衡量)，會隨著經驗E的增加而提升。)\n'

In [3]:
'''
機器學習的模型可在分為:
[監督式學習]:訓練資料中具備以實現的數值或標籤。
迴歸:數值預測的任務。
分類:類別預測的任務。
[非監督式學習]:訓練資料中「不」具備任何的數值或標籤。
'''

'\n機器學習的模型可在分為:\n[監督式學習]:訓練資料中具備以實現的數值或標籤。\n迴歸:數值預測的任務。\n分類:類別預測的任務。\n[非監督式學習]:訓練資料中「不」具備任何的數值或標籤。\n'

In [4]:
'''
模型(Model)是一個類似於「函數」的概念，由參數與運算組成。
模型的參數以及運算可以透過不同的方式生成，生成方式包含規則敘述與歷史資料訓練。

透過規則敘述生成參數以及運算，稱為基於規則模型(Rule-based medel)或稱專家模型。
透過歷史資料訓練生成參數以及運算，稱為基於演算法的模型(Algorithm-based medel)或稱基於機器學習的模型。

基於規則模型:問題能用人類語言描述邏輯、撰寫規則。答案不能容忍誤差。給定整數判斷它是否為奇數、偶數或質數。
基於演算法的模型:問題非領域專家不容易描述邏輯、撰寫規則。答案能夠容忍誤差。給定圖片判斷是貓或狗、給定房屋資訊預測房價。
'''

'\n模型(Model)是一個類似於「函數」的概念，由參數與運算組成。\n模型的參數以及運算可以透過不同的方式生成，生成方式包含規則敘述與歷史資料訓練。\n\n透過規則敘述生成參數以及運算，稱為基於規則模型(Rule-based medel)或稱專家模型。\n透過歷史資料訓練生成參數以及運算，稱為基於演算法的模型(Algorithm-based medel)或稱基於機器學習的模型。\n\n基於規則模型:問題能用人類語言描述邏輯、撰寫規則。答案不能容忍誤差。給定整數判斷它是否為奇數、偶數或質數。\n基於演算法的模型:問題非領域專家不容易描述邏輯、撰寫規則。答案能夠容忍誤差。給定圖片判斷是貓或狗、給定房屋資訊預測房價。\n'

In [5]:
'''
關於訓練、驗證與測試:
機器學習專案中的訓練、驗證來自具備已實現數值或標籤資料集。
測試則來自未實現數值或標籤資料集。
在從未見過的測試資料上之表現將決定他是否會被部署到正式環境開始運作。
'''

'\n關於訓練、驗證與測試:\n機器學習專案中的訓練、驗證來自具備已實現數值或標籤資料集。\n測試則來自未實現數值或標籤資料集。\n在從未見過的測試資料上之表現將決定他是否會被部署到正式環境開始運作。\n'

In [6]:
'''
減少訓練誤差的具體做法:
增加梯度遞減的訓練次數。
透過交叉驗證(Cross validation)的技巧消弭訓練與驗證資料切割所造成的誤差。
增加特徵矩陣的欄位。

減少訓練誤差與測試誤差的間距:
引用正規化（Regularization）的技巧。
減少訓練誤差的過程，很有可能伴隨而來的是驗證或測試誤差的升高。
模型對於訓練資料過於熟悉，而降低了它的泛化能力。
這樣的狀態我們稱之為「過度配適」（Overfitting）。
'''

'\n減少訓練誤差的具體做法:\n增加梯度遞減的訓練次數。\n透過交叉驗證(Cross validation)的技巧消弭訓練與驗證資料切割所造成的誤差。\n增加特徵矩陣的欄位。\n\n減少訓練誤差與測試誤差的間距:\n引用正規化（Regularization）的技巧。\n減少訓練誤差的過程，很有可能伴隨而來的是驗證或測試誤差的升高。\n模型對於訓練資料過於熟悉，而降低了它的泛化能力。\n這樣的狀態我們稱之為「過度配適」（Overfitting）。\n'

In [7]:
'''
Scikit-learn 是 Python 機器學習的第三方模組，
透過它可以進行監督式以及非監督式學習，提供了模型訓練、資料預處理、模型選擇以及模型評估等功能。

Scikit-Learn 應用程式介面設計原則:
一致性:每個轉換器類別都有 fit_transform() 方法。
可檢查性:每個轉換器或預測器都有屬性讓使用者檢視轉換或預測的規則。
不擴增新類別。
可組合性。
合理預設參數:每個轉換器、預測器都可以用預設參數建立物件。
'''

'\nScikit-learn 是 Python 機器學習的第三方模組，\n透過它可以進行監督式以及非監督式學習，提供了模型訓練、資料預處理、模型選擇以及模型評估等功能。\n\nScikit-Learn 應用程式介面設計原則:\n一致性:每個轉換器類別都有 fit_transform() 方法。\n可檢查性:每個轉換器或預測器都有屬性讓使用者檢視轉換或預測的規則。\n不擴增新類別。\n可組合性。\n合理預設參數:每個轉換器、預測器都可以用預設參數建立物件。\n'

In [8]:
'''
轉換器與預測器是 Scikit-Learn 所創造最重要的兩種類別:
轉換器:用來預處理資料。
預測器:用來訓練模型、生成規則w。

使用 Scikit-Learn 轉換器的標準步驟:
1.準備欲轉換的特徵矩陣X或目標陣列y。
2.建立轉換器類別的物件。
3.將欲轉換的特徵矩陣X或目標陣列y輸入transformer.fit_transform()。
4.檢查轉換結果。
'''

'\n轉換器與預測器是 Scikit-Learn 所創造最重要的兩種類別:\n轉換器:用來預處理資料。\n預測器:用來訓練模型、生成規則w。\n\n使用 Scikit-Learn 轉換器的標準步驟:\n1.準備欲轉換的特徵矩陣X或目標陣列y。\n2.建立轉換器類別的物件。\n3.將欲轉換的特徵矩陣X或目標陣列y輸入transformer.fit_transform()。\n4.檢查轉換結果。\n'

In [9]:
# 使用 Scikit-Learn 轉換器 PolynomialFeatures 生成一個指定次方數的特徵多項式矩陣。

import pandas as pd
from sklearn.preprocessing import PolynomialFeatures # 多次多項特徵

csv_url = "https://raw.githubusercontent.com/yaojenkuo/ml-newbies/master/player_stats.csv"
player_stats = pd.read_csv(csv_url)
X = player_stats["heightMeters"].values.reshape(-1, 1) # step 1
polynomial_features = PolynomialFeatures()             # step 2
X_transformed = polynomial_features.fit_transform(X)   # step 3
print(X_transformed[:5])                               # step 4

[[1.     2.03   4.1209]
 [1.     2.11   4.4521]
 [1.     2.06   4.2436]
 [1.     1.9    3.61  ]
 [1.     1.98   3.9204]]

In [10]:
player_stats.head()

,firstName,lastName,temporaryDisplayName,personId,teamId,jersey,isActive,pos,heightFeet,heightInches,...,ftm,fta,pFouls,points,gamesPlayed,gamesStarted,plusMinus,min,dd2,td3
0,Precious,Achiuwa,"Achiuwa, Precious",1630173,1610612748,5.0,True,F,6,8,...,56.0,110.0,91.0,304.0,61.0,4.0,-116.0,737.0,3.0,0.0
1,Steven,Adams,"Adams, Steven",203500,1610612740,12.0,True,C,6,11,...,936.0,1708.0,1497.0,5629.0,588.0,524.0,1638.0,15812.0,125.0,1.0
2,Bam,Adebayo,"Adebayo, Bam",1628389,1610612748,13.0,True,C-F,6,9,...,842.0,1141.0,668.0,3549.0,287.0,183.0,258.0,7840.0,91.0,5.0
3,Ty-Shon,Alexander,"Alexander, Ty-Shon",1630234,1610612756,0.0,True,G,6,3,...,1.0,2.0,2.0,9.0,15.0,0.0,-8.0,47.0,0.0,0.0
4,Nickeil,Alexander-Walker,"Alexander-Walker, Nickeil",1629638,1610612740,6.0,True,G,6,6,...,73.0,103.0,145.0,775.0,93.0,14.0,-105.0,1597.0,0.0,0.0

In [11]:
player_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 50 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   firstName             503 non-null    object
 1   lastName              503 non-null    object
 2   temporaryDisplayName  503 non-null    object
 3   personId              503 non-null    int64
 4   teamId                503 non-null    int64
 5   jersey                499 non-null    float64
 6   isActive              503 non-null    bool
 7   pos                   503 non-null    object
 8   heightFeet            503 non-null    int64
 9   heightInches          503 non-null    int64
 10  heightMeters          503 non-null    float64
 11  weightPounds          503 non-null    int64
 12  weightKilograms       503 non-null    float64
 13  dateOfBirthUTC        503 non-null    object
 14  nbaDebutYear          500 non-null    float64
 15  yearsPro              503 non-null    int64
 16  collegeName           503 non-null    object
 17  lastAffiliation       502 non-null    object
 18  country               502 non-null    object
 19  isallStar             0 non-null      float64
 20  tpp                   503 non-null    float64
 21  ftp                   503 non-null    float64
 22  fgp                   503 non-null    float64
 23  ppg                   503 non-null    float64
 24  rpg                   503 non-null    float64
 25  apg                   503 non-null    float64
 26  bpg                   503 non-null    float64
 27  mpg                   503 non-null    float64
 28  spg                   503 non-null    float64
 29  assists               500 non-null    float64
 30  blocks                500 non-null    float64
 31  steals                500 non-null    float64
 32  turnovers             500 non-null    float64
 33  offReb                500 non-null    float64
 34  defReb                500 non-null    float64
 35  totReb                500 non-null    float64
 36  fgm                   500 non-null    float64
 37  fga                   500 non-null    float64
 38  tpm                   500 non-null    float64
 39  tpa                   500 non-null    float64
 40  ftm                   500 non-null    float64
 41  fta                   500 non-null    float64
 42  pFouls                500 non-null    float64
 43  points                500 non-null    float64
 44  gamesPlayed           500 non-null    float64
 45  gamesStarted          500 non-null    float64
 46  plusMinus             500 non-null    float64
 47  min                   500 non-null    float64
 48  dd2                   500 non-null    float64
 49  td3                   500 non-null    float64
dtypes: bool(1), float64(35), int64(6), object(8)
memory usage: 193.2+ KB

In [12]:
X = player_stats["heightMeters"].values.reshape(-1, 1)
# X = player_stats[["heightMeters","weightKilograms"]].values
print(X.shape)
# print(X)
print(X[:5])

(503, 1)
[[2.03]
 [2.11]
 [2.06]
 [1.9 ]
 [1.98]]

In [13]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_features = PolynomialFeatures() # 合理預設參數(degree = 2)
X_transformed = polynomial_features.fit_transform(X) # [X0,身高公尺,身高公尺的平方]
print(X_transformed.shape)
# print(X_transformed)
print(X_transformed[:5])

(503, 3)
[[1.     2.03   4.1209]
 [1.     2.11   4.4521]
 [1.     2.06   4.2436]
 [1.     1.9    3.61  ]
 [1.     1.98   3.9204]]

In [14]:
# 使用 Scikit-Learn 轉換器 StandardScaler 生成一個經過 z-score 標準化的特徵矩陣。

mu = X.mean()
sigma = X.std()
print(mu)
print(sigma)
z_score = (X - mu) / sigma
# print(z_score)
print(z_score[:5])

1.9887673956262424
0.08491412789330907
[[ 0.48558003]
 [ 1.42770829]
 [ 0.83887812]
 [-1.04537841]
 [-0.10325014]]

In [15]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler() # 合理預設參數
X_transformed = standard_scaler.fit_transform(X) # 一致性
# print(X_transformed)
print(X_transformed[:5])

[[ 0.48558003]
 [ 1.42770829]
 [ 0.83887812]
 [-1.04537841]
 [-0.10325014]]

In [16]:
print(polynomial_features.degree) # 可檢查性

2

In [17]:
print(standard_scaler.mean_) # 可檢查性
print(standard_scaler.scale_) # 可檢查性

[1.9887674]
[0.08491413]

In [18]:
print(type(standard_scaler.mean_)) # 不擴增新類別
print(type(standard_scaler.scale_)) # 不擴增新類別

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [19]:
'''
主成分分析(Principal Component Analysis, PCA):為一種常用的降低數據維度(Dimensionality reduction)的手法。
主要的核心概念是用最少的維度來呈現原本高維度數據的訊息:
將原本p維的特徵(features)以k維的線性組合來表達(k < p)，
藉由找到的k維新特徵，能夠捕捉原本p維數據中的大部分特性來解釋數據。
換言之，希望能夠在盡量保有原始數據訊息的情況下，以更精簡化的形式來呈現原始數據。
'''

'\n主成分分析(Principal Component Analysis, PCA):為一種常用的降低數據維度(Dimensionality reduction)的手法。\n主要的核心概念是用最少的維度來呈現原本高維度數據的訊息:\n將原本p維的特徵(features)以k維的線性組合來表達(k < p)，\n藉由找到的k維新特徵，能夠捕捉原本p維數據中的大部分特性來解釋數據。\n換言之，希望能夠在盡量保有原始數據訊息的情況下，以更精簡化的形式來呈現原始數據。\n'

In [20]:
'''
主成分分析的步驟:
1.對數據做標準化。
2.建立共變異數矩陣。
3.分解共變異數矩陣為特徵向量及特徵值。
4.排序特徵值並且以該順序排列特徵向量。
5.映射數據至主成分。
'''

'\n主成分分析的步驟:\n1.對數據做標準化。\n2.建立共變異數矩陣。\n3.分解共變異數矩陣為特徵向量及特徵值。\n4.排序特徵值並且以該順序排列特徵向量。\n5.映射數據至主成分。\n'

In [21]:
player_stats.head()

,firstName,lastName,temporaryDisplayName,personId,teamId,jersey,isActive,pos,heightFeet,heightInches,...,ftm,fta,pFouls,points,gamesPlayed,gamesStarted,plusMinus,min,dd2,td3
0,Precious,Achiuwa,"Achiuwa, Precious",1630173,1610612748,5.0,True,F,6,8,...,56.0,110.0,91.0,304.0,61.0,4.0,-116.0,737.0,3.0,0.0
1,Steven,Adams,"Adams, Steven",203500,1610612740,12.0,True,C,6,11,...,936.0,1708.0,1497.0,5629.0,588.0,524.0,1638.0,15812.0,125.0,1.0
2,Bam,Adebayo,"Adebayo, Bam",1628389,1610612748,13.0,True,C-F,6,9,...,842.0,1141.0,668.0,3549.0,287.0,183.0,258.0,7840.0,91.0,5.0
3,Ty-Shon,Alexander,"Alexander, Ty-Shon",1630234,1610612756,0.0,True,G,6,3,...,1.0,2.0,2.0,9.0,15.0,0.0,-8.0,47.0,0.0,0.0
4,Nickeil,Alexander-Walker,"Alexander-Walker, Nickeil",1629638,1610612740,6.0,True,G,6,6,...,73.0,103.0,145.0,775.0,93.0,14.0,-105.0,1597.0,0.0,0.0

In [22]:
import numpy as np

# 對數據做標準化
# 可以用 StandardScaler 取代
def standardize(X):
    mean_X = np.mean(X, axis = 0)
    std_X = np.std(X, axis = 0)
    return (X - mean_X) / std_X


# 建立共變異數矩陣
# 可以用 np.cov() 取代
def covariance_matrix(X):
    m = X.shape[0]
    X_T = np.transpose(X)
    X_T_dot_X = X_T.dot(X) # (n, m) dot (m, n)
    return X_T_dot_X / (m - 1)


# 分解共變異數矩陣為特徵向量及特徵值
from numpy.linalg import eigh

def get_eig_vals_vecs(X):
    X_standard = standardize(X)
    cov_mat = covariance_matrix(X_standard)
    eig_vals, eig_vecs = eigh(cov_mat)
    return eig_vals, eig_vecs # 回傳特徵值(Eigenvalue)與特徵向量(Eigenvector)。


# 排序特徵值並且以該順序排列特徵向量
def get_principal_components(eigen_vals, eigen_vecs, k=2): # 降維要降到2維自己決定，k=2。
    sort_index = np.argsort(eigen_vals)[::-1]
    principal_components = eigen_vecs[:,sort_index]
    return principal_components[:, 0:k]


# 映射數據至主成分
def project_with_principal_components(X, principal_components):
    X_proj = X.dot(principal_components)
    return X_proj

In [29]:
X = player_stats[["heightMeters", "weightKilograms", "ppg", "rpg", "apg", "bpg"]].values
print(X.shape)

eig_vals, eig_vecs = get_eig_vals_vecs(X)
print(eig_vals)
print(eig_vecs)

principal_components = get_principal_components(eig_vals, eig_vecs)
print(principal_components)

(503, 6)
[0.16373274 0.22136132 0.22834305 0.43765901 1.98487537 2.9759807 ]
[[-0.03871383 -0.7378536  -0.28341712 -0.23561033 -0.33082153 -0.45693865]
 [ 0.21502596  0.5940849  -0.06046672 -0.56075055 -0.25323095 -0.46755069]
 [ 0.47490386 -0.25944978  0.51378923 -0.19269957  0.58115027 -0.26135034]
 [-0.76312297  0.10823753  0.28228868  0.11304874  0.2303637  -0.51028777]
 [-0.09095769  0.04788061 -0.71467705 -0.20748724  0.66000909  0.00281235]
 [ 0.36891927  0.14599005 -0.2481712   0.73285912  0.00401739 -0.4938602 ]]
[[-0.45693865 -0.33082153]
 [-0.46755069 -0.25323095]
 [-0.26135034  0.58115027]
 [-0.51028777  0.2303637 ]
 [ 0.00281235  0.66000909]
 [-0.4938602   0.00401739]]

In [32]:
project_X = project_with_principal_components(standardize(X), principal_components)
project_X.shape

(503, 2)

In [34]:
# 與 Scikit-Learn 的 PCA 類別對照
from sklearn.decomposition import PCA

X = player_stats[["heightMeters", "weightKilograms", "ppg", "rpg", "apg", "bpg", "mpg", "spg"]]
standardize_X = standardize(X)
pca = PCA(n_components=2)
pca.fit(standardize_X)
print(pca.components_.T)

[[ 0.09356129  0.5405206 ]
 [ 0.13818604  0.50663074]
 [ 0.45920451 -0.11706303]
 [ 0.42149541  0.26861885]
 [ 0.34079429 -0.36918406]
 [ 0.28699409  0.38382527]
 [ 0.47404909 -0.13309185]
 [ 0.40049325 -0.25292445]]

In [35]:
print(pca.fit_transform(standardize_X))

[[-1.44589649  1.25240962]
 [ 2.02798202  2.67058885]
 [ 2.63744516  1.51229563]
 ...
 [-3.57844588  2.63263971]
 [ 0.87499066  1.85178204]
 [ 0.09906745  2.52969675]]

In [ ]:
# 迴歸模型